name: API Gateway CI


on:

  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev



jobs:


  build:


    runs-on: ubuntu-latest


    steps:


      - name: Checkout
        uses: actions/checkout@v4



      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25



      - name: Build

        run: |
          
          chmod +x gradlew
          ./gradlew clean build



      - name: Docker Build

        run: |
          
          docker build \
          -t donaton-api-gateway .