spring.application.name=auth

# SERVER
server.port=8082

# ACTUATOR
management.endpoints.web.exposure.include=health,info

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT
jwt.expiration=3600000