spring.application.name=api-gateway

server.port=8090

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.server.webmvc.routes[0].id=bff
spring.cloud.gateway.server.webmvc.routes[0].uri=http://bff:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/**