spring.application.name=bff

server.port=8080

# MICROSERVICIOS
auth.service.url=http://ms-auth:8082
user.service.url=http://ms-user:8081
donation.service.url=http://ms-donation:8083
campaign.service.url=http://ms-campaign:8084

# ACTUATOR

management.endpoints.web.exposure.include=health,info

# SWAGGER

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true